server:
  port : 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mint-db.cuytor0vm4dq.us-east-1.rds.amazonaws.com:3306/mint
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file: 
    name: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"  
  level:
    root: INFO   
mqtt:
  username: mint
  port: '1883'
  hostname: 3.89.90.95
  password: mint
  subTopic: mintsub
  pubTopic: mintpub
  automaticReconnect: true
  cleanSession: true
  connectionTimeout: 10
  clientId: mintonomous-mqtt
